#define pointofsale 0
#define features 0
#define definitionsacronymsandabbreviations 0
#define shortcutkeys 0
#define posautomaticupdates 0
#define posuserinterface 110
#define homebuttonsandstatusbar 120
#define statusbar 130
#define listviews 140
#define discounts 150
#define changepassword 0
#define hintsandtips 0
#define login 0
#define notes 0
#define viewnotes 0
#define displaylanguage 160
#define standardSettings 170
#define loginsettings 171
#define automaticlogin 172
#define plugins 173
#define editplugin 0
#define standardicons 180
#define administrationsettings 1000
#define smsreminderalerts 1010
#define invoiceSettings 1020
#define invoiceSettingsHeader 1021
#define invoiceSettingsFooter 1022
#define administrationSettingsProducts 1030
#define staffLeaveSettings 1040
#define staffcommissionsettings 1050
#define commissionpoolsettings 1051
#define adminclientcommissionsettings 1052
#define adminaffiliatesettings 0
#define admincashdrawersettings 0
#define diarysmsalertoptions 0
#define invoicesettings 0
#define invoiceheadersettings 0
#define invoicefootersettings 0
#define ordermanagersettings 0
#define ordermanagerrecordeddelivery 0
#define ordermanagerlabelprintingsettings 0
#define adminmarketingsettings 0
#define marketingmailchimpsettings 0
#define stockcontrolsettings 0
#define stockcontrolautomaticstockreordering 0
#define websitesettings 0
#define administrationusersettings 0
#define administrationusersettingsgeneral 0
#define administrationusersettingsdictionary 0
#define administrationusersettingslanguage 0
#define administrationusersettingspricedata 0
#define administrationusersettingstillsettings 0
#define currencywatchsettings 0
#define userdiarysettings 0
#define administrationstaff 0
#define createstaffmember 0
#define createstaffstep1 0
#define createstaffstep2 0
#define createstaffstep3 0
#define createstaffstep4 0
#define createstaffstep5 0
#define removestaff 0
#define staffdetails 0
#define staffcontactdetails 0
#define staffemploymentdetails 0
#define staffpersonaldetails 0
#define staffleaveholiday 0
#define staffviewleave 0
#define staffrequestleave 0
#define staffapproveleave 0
#define staffauthoriseleave 0
#define staffsicknessdetails 0
#define staffnewsicknessrecord 0
#define staffsicknesscreatestep1 0
#define staffsicknesscreatestep2 0
#define staffsicknesscreatestep3 0
#define staffsicknesscreatestep4 0
#define staffviewsicknessrecord 0
#define staffsicknessreturntowork 0
#define staffsicknessstatistics 0
#define staffsicknessselectappointment 0
#define staffemeregencycontact 0
#define staffdrivinglicence 0
#define staffdiarysettings 0
#define staffworkinghours 0
#define staffworkinghoursedit 0
#define stafftreatments 0
#define staffpospermissions 0
#define staffcommission 0
#define staffclients 0
#define customers 0
#define createcustomer 0
#define viewcustomerdetails 0
#define viewcustomerorders 0
#define viewcustomerinvoices 0
#define viewcustomersupporttickets 0
#define customermarketingpreferences 0
#define customerdeliveryaddress 0
#define viewcustomernotes 0
#define viewcustomerappointments 0
#define editcustomergolduser 0
#define editcustomersalonowners 0
#define editcustomerpermissions 0
#define exportcustomers 0
#define exportcustomerstep1 0
#define exportcustomerstep2 0
#define exportcustomerstep3 0
#define exportcustomerstep4 0
#define exportcustomerstep5 0
#define exportcustomerstep6 0
#define mergecustomers 0
#define products 1020
#define producteditdetails 1105
#define producteditsettings 1110
#define producteditproductitems 1115
#define newproductitem 0
#define editproductitem 0
#define pricecalculator 0
#define producteditproductgroups 1125
#define newproduct 0
#define productedittopsellingproducts 1120
#define invalidproductsku 0
#define administrationproductgroups 0
#define editproductgroups 1210
#define editproductgroupmobile 0
#define diary 0
#define diarytoolbar 0
#define diarydateselection 0
#define diaryimageoverlays 0
#define diarysalontreatments 0
#define diaryeditsalontreatments 0
#define diaryedittreatmentstaffmembers 0
#define diaryadvancedsettings 0
#define diaryadvancedsettingsgeneral 0
#define diaryadvancedsettingscolours 0
#define diaryadvancedsettingsimageoverlays 0
#define diaryadvancedsettingsautohide 0
#define diaryadvancedsettingstimes 0
#define diaryadvancedsettingsadvanced 0
#define diaryappointmentmenu 0
#define diaryappointmentstatus 0
#define diarycreateoreditappointment 0
#define diarycreateoredittreatmentaddtreatment 0
#define diarycreateoreditappointmentprevioustreatments 0
#define diarycloneappointment 0
#define diaryappointmenthistory 0
#define diaryappointmentchanges 0
#define diarycreditcarddetails 0
#define diarynewappointments 0
#define diaryreports 0
#define diarynewappointmentwizard 0
#define diarynewappointmentwizardstep1 0
#define diarynewappointmentwizardstep2 0
#define diarynewappointmentwizardstep3 0
#define diarywaitinglist 0
#define diarywaitingliststep1 0
#define diarywaitingliststep2 0
#define diarywaitingliststep3 0
#define diarywaitingliststep4 0
#define diarysmsalerts 0
#define diarysmsalertsstep1 0
#define diarysmsalertsstep2 0
#define diarysmsalertsstep3 0
#define till 0
#define tillapplydiscounts 0
#define tillcompletingasale 0
#define tillenteringpayment 0
#define tillredeemvoucher 0
#define tillcashpayment 0
#define tillsplitpayments 0
#define tillcardpayments 0
#define tillchequepayments 0
#define tillcustomvatrate 0
#define tillassignbarcodes 0
#define invoices 0
#define invoicemanager 0
#define invoiceview 0
#define invoiceviewchangesalesperson 0
#define invoiceviewcancelinvoice 0
#define invoiceviewissuerefund 0
#define orders 0
#define orderview 0
#define orderscreateorder 0
#define orderscreateorderopensavedorder 0
#define ordersfindorders 0
#define ordersviewordersreceived 0
#define ordersviewunpaidorders 0
#define ordersdispatchorders 0
#define orderstrackingreference 0
#define stockcontrol 0
#define stockcontrolstockin 0
#define stockcontrolstockout 0
#define stockcontrolstockaudit 0
#define stockcontrolcreatestock 0
#define stockcreatestockconfirm 0
#define stockcontrolstockhistory 0
#define stockcontrolsetautomaticstockreordering 0
#define administrationdiscountcoupons 0
#define discountcouponsstep1 1305
#define discountcouponsstep2 1310
#define discountcouponsstep3 1315
#define discountcouponsstep4 1320
#define discountcouponssummary 1325
#define admincashdrawer 0
#define admincashdrawertill 0
#define admincashdrawerverifytill 0
#define admincashdrawersafe 0
#define admincashdrawerverifysafe 0
#define admincashdrawerpettycash 0
#define admincashdrawerpettycashverify 0
#define vouchermanagement 0
#define voucherscreatevouchers 0
#define systememails 0
#define marketing 0
#define marketingcreatecampaign 0
#define marketingcampaignname 0
#define marketingselecttemplate 0
#define marketinglandingpage 0
#define marketingsocialmedialinks 0
#define marketingmenuitems 0
#define marketingpreview 0
#define marketingcampaign 0
#define marketingrepeatcampaign 0
#define marketingupdatemarketingfiles 0
#define countries 0
#define countriesaddressoptions 0
#define trainingschedule 0
#define trainingschedulecreatestep1 0
#define trainingschedulecreatestep2 0
#define trainingschedulecreatestep3 0
#define trainingscheduleedittrainingcourse 0
#define trainingscheduleeditcourseaddattendees 0
#define commission 0
#define commissionpools 0
#define administrationcommissionpools 0
#define administrationcommissionpoolsgeneratedata 0
#define administrationcommissionpooldata 0
#define adminpaycommission 0
#define paycommissionpoolstep1 0
#define paycommissionpoolstep2 0
#define paycommissionpoolstep3 0
#define paycommissionpoolstep4 0
#define paycommissionpoolstep5 0
#define adminstaffaccountcommission 0
#define adminclientcommissiongeneratedata 0
#define adminaccountcommissiondata 0
#define adminclientcommissionbonuspayments 0
#define adminclientcommissionbonuspaystep1 0
#define adminclientcommissionbonuspaystep2 0
#define adminclientcommissionbonuspaystep3 0
#define adminclientcommissionbonuspaystep4 0
#define adminclientcommissionbonuspaystep5 0
#define affiliatemarketingandcommission 0
#define adminaffiliatecommissionsales 0
#define adminaffiliateseolinks 0
#define adminsettingupaffiliates 0
#define adminaffiliatecreatesettings 0
#define affiliatecommissiondata 0
#define adminaffiliatepaycommission 0
#define adminaffiliatepaycommissionstep1 0
#define adminaffiliatepaycommissionstep2 0
#define adminaffiliatepaycommissionstep3 0
#define export 0
#define exportsage 0
#define databasebackup 0
#define currencywatch 0
#define updateallimages 0
#define automaticruleupdates 0
#define automaticrulescreaterulestep1 0
#define automaticrulescreaterulestep2 0
#define automaticrulescreaterulestep3 0
#define automaticrulescreaterulestep4 0
#define automaticrulescreaterulestep5 0
#define websitesalons 0
#define websitesalonseditsalons 0
#define websitesalonseditsalonsgeneral 0
#define websitesalonseditsalonssettings 0
#define websitesaloneditvip 0
#define websitesalonseditsalonstype 0
#define websitesalonseditsalonsopeningtimes 0
#define websitesalonowners 0
#define websitesalonownerssalonownerdetails 0
#define websitesalonownerssalonownerpermissions 0
#define websitesalontosalonowners 0
#define websitesalonupdates 0
#define websalonsselectsalon 0
#define websitetreatments 0
#define websiteedittreatments 0
#define websitetreatmentstreatmentgroups 0
#define websitetreatmentsedittreatmentgroups 0
#define websitedistributors 0
#define helpdesk 0
#define helpdeskviewticket 0
#define customercomments 0
#define websitemissinglinks 0
#define websitemissinglinksedit 0
#define websitecelebrities 0
#define websitetipsandtricks 0
#define websitetipsandtricksedit 0
#define websitevideoadministration 0
#define reports 0
#define reportsclientbirthday 0
#define reportssalon 0
#define reportsstockcontrol 0
#define reportsproducts 0
#define initialsetupstep1 0
#define initialsetupstep2 0
#define initialsetupstep3 0
#define initialsetupstep4 0
#define initialsetupfinal 0
#define memberlevels 0
#define parameters 0

