#define pointofsale 0
#define features 0
#define definitionsacronymsandabbreviations 0
#define shortcutkeys 0
#define posuserinterface 110
#define homebuttonsandstatusbar 120
#define listviews 140
#define statusbar 0
#define discounts 0
#define displaylanguage 0
#define settings1 0
#define loginsettings 0
#define automaticlogin 0
#define plugins 0
#define standardicons 0
#define administrationsettings 1010
#define smsreminderalerts 0
#define invoice 0
#define invoiceheader 0
#define invoicefooter 0
#define administrationsettingsproducts 0
#define administrationusersettings 0
#define administrationusersettingsgeneral 0
#define administrationusersettingsdictionary 0
#define administrationusersettingslanguage 0
#define administrationusersettingspricedata 0
#define administrationusersettingstillsettings 0
#define products 1020
#define producteditdetails 1105
#define producteditsettings 1110
#define producteditproductitems 1115
#define editproductitem 0
#define pricecalculator 0
#define producteditproductgroups 1125
#define productedittopsellingproducts 1120
#define administrationproductgroups 0
#define editproductgroups 1210
#define administrationdiscountcoupons 0
#define discountcouponsstep1 1305
#define discountcouponsstep2 1310
#define discountcouponsstep3 1315
#define discountcouponsstep4 1320
#define discountcouponssummary 1325

