//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heavenskincare.WebsiteTemplate.Members {
    
    
    public partial class SupportTickets {
        
        /// <summary>
        /// LeftContainerControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Heavenskincare.WebsiteTemplate.Controls.LeftContainerControl LeftContainerControl1;
        
        /// <summary>
        /// ProfileSupportTickets1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Heavenskincare.WebsiteTemplate.Members.Controls.ProfileSupportTickets ProfileSupportTickets1;
    }
}
